type User {
  id: ID!
  username: String!
  posts: [Post] # the list of Posts by this user
}

type Post {
  id: ID!
  title: String
  author: User!
}

# the schema allows the following query:
type Query {
  user(id: ID!): User!
  me: User!
  posts: [Post]
}

# this schema allows the following mutation:
type Mutation {
  signup(username: String!, password: String!): User!
  signin(username: String!, password: String!): String!
}
