type User {
  _id: ID!
  username: String!
  posts: [Post] # the list of Posts by this user
}

type Post {
  _id: ID!
  title: String
  author: User!
}

# the schema allows the following query:
type Query {
  posts: [Post]
  user(_id: ID!): User
}

# this schema allows the following mutation:
# type Mutation {
# }
